const allTerms = [
  { term: "Access Control", coc: "COC 2", definition: "A security technique that regulates who or what can access network resources." },
  { term: "Access Control List", coc: "COC 3", definition: "A list of permissions that specify which users can access certain system resources." },
  { term: "Access Point", coc: "COC 2", definition: "A networking hardware device that allows wireless devices to connect to a wired network." },
  { term: "Access Time", coc: "COC 1", definition: "The time interval between a data request and its delivery from a storage device." },
  { term: "Account Lockout", coc: "COC 3", definition: "A security feature that disables a user account after multiple failed login attempts." },
  { term: "Active Directory", coc: "COC 2", definition: "A Microsoft service used to manage users, computers, and resources within a network." },
  { term: "Adapter", coc: "COC 2", definition: "A device that enables one type of hardware or interface to work with another." },
  { term: "Adapter Card", coc: "COC 1", definition: "A hardware component inserted into a slot to add functionality to a computer." },
  { term: "Address Resolution Protocol", coc: "COC 2", definition: "A network protocol used to map an IP address to a physical machine address." },
  { term: "Administrator Account", coc: "COC 3", definition: "A user account with full permissions to configure and manage system settings." },
  { term: "Airflow", coc: "COC 1", definition: "The movement of air through a computer case to regulate temperature." },
  { term: "Algorithm", coc: "COC 1", definition: "A set of step-by-step instructions designed to perform a specific task." },
  { term: "Anomaly Detection", coc: "COC 2", definition: "The process of identifying unusual patterns or behaviors in network traffic." },
  { term: "Anti-Static Mat", coc: "COC 1", definition: "A grounded mat that protects electronic components during handling." },
  { term: "Antivirus Server", coc: "COC 3", definition: "A centralized system that provides virus protection across networked computers." },
  { term: "Antivirus Software", coc: "COC 2", definition: "A program designed to detect and remove malicious software from a computer system." },
  { term: "Apache", coc: "COC 3", definition: "A widely used open-source web server software." },
  { term: "Application Gateway", coc: "COC 2", definition: "A firewall that filters network traffic based on specific application-level protocols." },
  { term: "Application Layer", coc: "COC 2", definition: "The top layer of the OSI model that provides network services to end users." },
  { term: "Application Server", coc: "COC 3", definition: "A server that hosts and runs specific business or web applications." },
  { term: "Application Software", coc: "COC 1", definition: "Programs designed to perform specific user-oriented tasks." },
  { term: "Archive", coc: "COC 1", definition: "A collection of historical data stored for long-term retention." },
  { term: "Audit Policy", coc: "COC 3", definition: "A configuration that defines which events are recorded in the security log." },
  { term: "Authentication", coc: "COC 1", definition: "The process of verifying the identity of a user or system." },
  { term: "Authentication Server", coc: "COC 2", definition: "A server that verifies the identity of users and devices before granting access." },
  { term: "Authorization", coc: "COC 3", definition: "The process of granting or denying user access to specific resources." },
  { term: "Auto-Negotiation", coc: "COC 2", definition: "A feature that allows network devices to automatically configure transmission parameters." },
  { term: "Backbone Network", coc: "COC 2", definition: "The central part of a network that connects multiple subnetworks for efficient data exchange." },
  { term: "Backup", coc: "COC 1", definition: "The process of creating a copy of data to prevent loss in case of system failure." },
  { term: "Backup Schedule", coc: "COC 3", definition: "A planned routine for regularly backing up important data." },
  { term: "Backup Server", coc: "COC 2", definition: "A server that stores copies of data and ensures recovery in case of failure." },
  { term: "Backup Utility", coc: "COC 1", definition: "Software designed to automate the process of data backup." },
  { term: "Backup Verification", coc: "COC 3", definition: "The process of ensuring that backup files are valid and restorable." },
  { term: "Bandwidth", coc: "COC 1", definition: "The maximum rate of data transfer across a network path." },
  { term: "Bandwidth Utilization", coc: "COC 2", definition: "The measurement of actual data transfer relative to the available bandwidth." },
  { term: "Basic Input/Output System", coc: "COC 1", definition: "Firmware that initializes and manages hardware during computer startup." },
  { term: "Batch File", coc: "COC 1", definition: "A script that executes a sequence of commands in an operating system." },
  { term: "Beep Code", coc: "COC 1", definition: "Audible signals from the BIOS indicating hardware status or errors during boot." },
  { term: "BIOS", coc: "COC 1", definition: "Firmware that initializes hardware during the computer startup process." },
  { term: "BIOS Setup Utility", coc: "COC 1", definition: "An interface used to configure system hardware settings." },
  { term: "Bit", coc: "COC 1", definition: "The smallest unit of data in computing, representing 0 or 1." },
  { term: "Bit Error Rate", coc: "COC 2", definition: "The percentage of bits that have errors relative to the total number of transmitted bits." },
  { term: "Bitrate", coc: "COC 2", definition: "The number of bits transmitted per second in a digital network." },
  { term: "Blade Server", coc: "COC 3", definition: "A compact modular server designed to fit into a rack chassis." },
  { term: "Bluetooth", coc: "COC 2", definition: "A short-range wireless technology used for data exchange between devices." },
  { term: "Boot Disk", coc: "COC 1", definition: "A removable media that starts the computer and loads an operating system." },
  { term: "Boot Loader", coc: "COC 3", definition: "A small program that loads the operating system into memory." },
  { term: "Boot Sequence", coc: "COC 1", definition: "The order in which devices are accessed during system startup." },
  { term: "Bridge", coc: "COC 1", definition: "A device that connects and filters traffic between two network segments." },
  { term: "Bridge Protocol Data Unit", coc: "COC 2", definition: "A message exchanged by switches to prevent loops in a network using the Spanning Tree Protocol." },
  { term: "Broadband", coc: "COC 2", definition: "A high-capacity transmission technique that allows multiple signals to be sent simultaneously." },
  { term: "Broadcast", coc: "COC 2", definition: "The transmission of data to all devices in a network segment." },
  { term: "Broadcast Domain", coc: "COC 2", definition: "A network segment where broadcast packets are sent to all devices." },
  { term: "Buffer", coc: "COC 1", definition: "A temporary memory area that stores data while it is being transferred." },
  { term: "Bus", coc: "COC 1", definition: "A communication system that transfers data between computer components." },
  { term: "Bus Topology", coc: "COC 2", definition: "A network topology where all devices are connected to a single central cable." },
  { term: "Cable Modem", coc: "COC 2", definition: "A device that provides internet access via a cable television network." },
  { term: "Cable Tie", coc: "COC 1", definition: "A plastic fastener used to organize and secure cables neatly." },
  { term: "Cache Memory", coc: "COC 1", definition: "A small, high-speed memory that stores frequently accessed data." },
  { term: "Case Fan", coc: "COC 1", definition: "A fan mounted on the computer case to maintain airflow and cooling." },
  { term: "CAT5e", coc: "COC 2", definition: "An enhanced twisted-pair cable standard supporting higher data transfer rates." },
  { term: "Category 5 Cable", coc: "COC 2", definition: "A type of twisted-pair cable used for Ethernet and other network standards." },
  { term: "Category 6 Cable", coc: "COC 2", definition: "An improved version of Cat5 cable, supporting higher frequencies for faster data transfer." },
  { term: "Cellular Network", coc: "COC 2", definition: "A communication network that provides wireless connectivity through cellular towers." },
  { term: "Certificate Authority", coc: "COC 3", definition: "An organization that issues and verifies digital security certificates." },
  { term: "Chipset", coc: "COC 1", definition: "A set of electronic components that manage communication between CPU and peripherals." },
  { term: "Circuit Switching", coc: "COC 2", definition: "A communication method that establishes a dedicated path between sender and receiver." },
  { term: "Client", coc: "COC 2", definition: "A computer or software that requests resources or services from a server." },
  { term: "Client-Server Model", coc: "COC 3", definition: "A network model in which clients request and servers provide services." },
  { term: "Client-Server Network", coc: "COC 2", definition: "A network model where client devices request services from a centralized server." },
  { term: "Cloud Computing", coc: "COC 2", definition: "The delivery of computing services over the internet." },
  { term: "Cloud Storage", coc: "COC 1", definition: "A service that stores digital data on remote servers accessed via the internet." },
  { term: "Cluster", coc: "COC 1", definition: "The smallest allocatable unit of disk space in a file system." },
  { term: "Cluster Node", coc: "COC 3", definition: "An individual computer participating in a server cluster." },
  { term: "Clustering", coc: "COC 3", definition: "A technique that links multiple servers to act as a single system for reliability." },
  { term: "CMOS", coc: "COC 1", definition: "A chip that stores BIOS configurations and system settings." },
  { term: "CMOS Battery", coc: "COC 1", definition: "A battery that powers BIOS memory to retain settings." },
  { term: "Coaxial Cable", coc: "COC 2", definition: "A type of electrical cable consisting of a central conductor, insulating layer, and shielding." },
  { term: "Collision Domain", coc: "COC 2", definition: "A network area where data packets can collide with each other during transmission." },
  { term: "Command Line Interface", coc: "COC 2", definition: "A text-based interface used to interact with the operating system or software." },
  { term: "Command Prompt", coc: "COC 1", definition: "A text-based system used to execute commands directly in the OS." },
  { term: "Command-Line Interface", coc: "COC 3", definition: "A text-based interface used to interact with operating systems or software." },
  { term: "Compression", coc: "COC 1", definition: "The process of reducing file size to save storage space or transfer time." },
  { term: "Computer Network", coc: "COC 2", definition: "A collection of interconnected devices that can share resources and data." },
  { term: "Computer Virus", coc: "COC 2", definition: "A malicious program that attaches itself to legitimate software and spreads when executed." },
  { term: "Configuration", coc: "COC 1", definition: "The arrangement and setup of hardware and software components." },
  { term: "Connection-Oriented Protocol", coc: "COC 2", definition: "A protocol that requires a connection before data transmission begins." },
  { term: "Connectionless Protocol", coc: "COC 2", definition: "A protocol that does not establish a connection before transmitting data." },
  { term: "Connectivity", coc: "COC 2", definition: "The state of being connected or able to communicate with other systems." },
  { term: "Console Cable", coc: "COC 2", definition: "A cable used to connect a computer to a network device for configuration." },
  { term: "Containerization", coc: "COC 3", definition: "A method of packaging software and its dependencies for consistent deployment." },
  { term: "Control Panel", coc: "COC 1", definition: "An interface used to configure and manage computer settings." },
  { term: "Cooling Fan", coc: "COC 1", definition: "A device that circulates air to cool internal components." },
  { term: "CPU", coc: "COC 1", definition: "The main processor that performs all the instructions of computer programs." },
  { term: "CPU Socket", coc: "COC 1", definition: "The connector on the motherboard that holds the CPU securely." },
  { term: "CPU Utilization", coc: "COC 3", definition: "The percentage of processing capacity currently in use on a server." },
  { term: "Crash", coc: "COC 1", definition: "A sudden failure that causes the computer or program to stop functioning properly." },
  { term: "Cross-Over Cable", coc: "COC 2", definition: "A type of Ethernet cable used to connect two similar devices directly." },
  { term: "Cursor", coc: "COC 1", definition: "A movable indicator on the screen showing where user input will appear." },
  { term: "Data Bus", coc: "COC 1", definition: "A pathway that transfers data between computer components." },
  { term: "Data Center", coc: "COC 3", definition: "A facility that houses servers and critical IT infrastructure." },
  { term: "Data Communication", coc: "COC 2", definition: "The process of exchanging data between two or more digital devices." },
  { term: "Data Encryption Standard", coc: "COC 2", definition: "An older symmetric-key algorithm for encrypting digital data." },
  { term: "Data Integrity", coc: "COC 2", definition: "The accuracy and consistency of data throughout its lifecycle." },
  { term: "Data Link Layer", coc: "COC 2", definition: "The second layer of the OSI model responsible for reliable data transfer across physical links." },
  { term: "Data Mirroring", coc: "COC 3", definition: "A technique that copies data in real time to ensure redundancy." },
  { term: "Database", coc: "COC 1", definition: "An organized collection of data stored and managed electronically." },
  { term: "Database Server", coc: "COC 2", definition: "A server dedicated to managing and providing access to databases." },
  { term: "Dedicated Server", coc: "COC 3", definition: "A physical server exclusively used by one client or application." },
  { term: "Default Gateway", coc: "COC 2", definition: "A network node that routes traffic from a local network to other networks." },
  { term: "Default Route", coc: "COC 2", definition: "A network route used when no specific route is found for a destination." },
  { term: "Defragmentation", coc: "COC 1", definition: "A process that reorganizes fragmented data on a disk to improve performance." },
  { term: "Demilitarized Zone", coc: "COC 2", definition: "A network area that separates an internal network from untrusted external networks." },
  { term: "Deployment Script", coc: "COC 3", definition: "A script that automates the installation and configuration of software." },
  { term: "Device Driver", coc: "COC 1", definition: "Software that allows communication between the operating system and hardware." },
  { term: "Device Manager", coc: "COC 1", definition: "A system utility for viewing and managing installed hardware devices." },
  { term: "DHCP", coc: "COC 2", definition: "Dynamic Host Configuration Protocol, which automatically assigns IP addresses to devices." },
  { term: "DHCP Lease", coc: "COC 3", definition: "A temporary IP address assignment given by a DHCP server." },
  { term: "DHCP Server", coc: "COC 3", definition: "A server that automatically assigns IP addresses to devices on a network." },
  { term: "Diagnostic Software", coc: "COC 1", definition: "A program used to detect and analyze hardware or software problems." },
  { term: "Diagnostic Tool", coc: "COC 1", definition: "Software or hardware used to identify and troubleshoot system errors." },
  { term: "Differential Backup", coc: "COC 3", definition: "A backup that saves changes made since the last full backup." },
  { term: "Digital Certificate", coc: "COC 2", definition: "An electronic document used to prove ownership of a public key." },
  { term: "Digital Signature", coc: "COC 2", definition: "An encrypted mark of authenticity that verifies data integrity and sender identity." },
  { term: "Directory", coc: "COC 1", definition: "A folder used to organize files and subfolders in a storage system." },
  { term: "Directory Service", coc: "COC 3", definition: "A system that stores and manages information about network resources." },
  { term: "Directory Services", coc: "COC 2", definition: "A system that stores, organizes, and provides access to network resource information." },
  { term: "Disassembly", coc: "COC 1", definition: "The careful process of removing and separating computer parts." },
  { term: "Disaster Recovery Plan", coc: "COC 3", definition: "A documented strategy to restore systems after a major failure." },
  { term: "Disk Cleanup", coc: "COC 1", definition: "A utility that removes temporary and unnecessary files to free up space." },
  { term: "Disk Drive", coc: "COC 1", definition: "A device that reads and writes data on magnetic or optical disks." },
  { term: "Disk Management", coc: "COC 1", definition: "A system tool used to partition and format storage drives." },
  { term: "Disk Partition", coc: "COC 3", definition: "A division of a hard drive into separate logical sections." },
  { term: "Distributed Denial of Service", coc: "COC 2", definition: "A cyberattack where multiple systems flood a target with traffic to disrupt services." },
  { term: "DNS", coc: "COC 2", definition: "Domain Name System, which translates domain names into IP addresses." },
  { term: "DNS Server", coc: "COC 2", definition: "A server that resolves domain names to their corresponding IP addresses." },
  { term: "Docker", coc: "COC 3", definition: "A popular platform for creating, deploying, and managing containers." },
  { term: "Domain", coc: "COC 1", definition: "A group of computers under a single administration and security policy." },
  { term: "Domain Controller", coc: "COC 3", definition: "A server responsible for managing user authentication and policies in a domain." },
  { term: "Download", coc: "COC 1", definition: "The process of receiving data from a remote system to a local device." },
  { term: "Download Speed", coc: "COC 2", definition: "The rate at which data is received from the internet." },
  { term: "Downtime", coc: "COC 3", definition: "A period when a server or service is unavailable." },
  { term: "Driver", coc: "COC 1", definition: "Software that enables communication between the operating system and hardware." },
  { term: "Driver Update", coc: "COC 1", definition: "Installing the latest version of software that manages hardware functionality." },
  { term: "Duplex", coc: "COC 2", definition: "A mode of communication allowing data to flow in both directions simultaneously." },
  { term: "Dust Filter", coc: "COC 1", definition: "A mesh component that prevents dust from entering the computer case." },
  { term: "Dynamic IP Address", coc: "COC 2", definition: "An IP address that is automatically assigned by a DHCP server and can change over time." },
  { term: "Dynamic Routing", coc: "COC 2", definition: "A routing method where routers automatically update paths based on network conditions." },
  { term: "Eavesdropping", coc: "COC 2", definition: "An unauthorized interception of private communication between devices." },
  { term: "Electrical Safety", coc: "COC 1", definition: "A set of procedures to prevent electrical hazards." },
  { term: "Encryption", coc: "COC 1", definition: "The process of converting readable data into an unreadable format to protect it." },
  { term: "Encryption Key", coc: "COC 2", definition: "A random string of data used to encrypt and decrypt digital information." },
  { term: "Environmental Monitoring", coc: "COC 3", definition: "The process of tracking temperature and humidity in a server room." },
  { term: "ESD Strap", coc: "COC 1", definition: "A wrist strap worn by technicians to prevent electrostatic damage." },
  { term: "Ethernet", coc: "COC 2", definition: "A common method of networking computers using wired connections." },
  { term: "Ethernet Cable", coc: "COC 1", definition: "A cable that connects devices within a local area network." },
  { term: "Event Log", coc: "COC 3", definition: "A record of system, security, and application events on a server." },
  { term: "Event Viewer", coc: "COC 3", definition: "A Windows tool for viewing system and security logs." },
  { term: "Execution", coc: "COC 1", definition: "The process of running or performing program instructions." },
  { term: "exFAT", coc: "COC 1", definition: "A modern file system optimized for flash drives and large files." },
  { term: "Expansion Slot", coc: "COC 1", definition: "A slot on the motherboard that allows installation of additional hardware cards." },
  { term: "Failback", coc: "COC 3", definition: "The process of returning operations to a primary system after recovery." },
  { term: "Failover", coc: "COC 3", definition: "The automatic transfer to a standby system in case of failure." },
  { term: "Failover Cluster", coc: "COC 3", definition: "A group of servers that provide continuous availability by automatically transferring workloads." },
  { term: "FAT32", coc: "COC 1", definition: "A file system compatible with multiple operating systems." },
  { term: "Fiber Optic Cable", coc: "COC 2", definition: "A cable that transmits data as light through glass or plastic fibers." },
  { term: "File Extension", coc: "COC 1", definition: "The suffix that identifies the file type and associated program." },
  { term: "File Server", coc: "COC 3", definition: "A server that stores and manages files for network users." },
  { term: "File Sharing", coc: "COC 2", definition: "The practice of distributing or providing access to digital files over a network." },
  { term: "File System", coc: "COC 1", definition: "A structure used by the operating system to organize and manage data on storage devices." },
  { term: "File Transfer Protocol", coc: "COC 2", definition: "A protocol used to transfer files between computers over a network." },
  { term: "Firewall", coc: "COC 1", definition: "A system that monitors and controls incoming and outgoing network traffic." },
  { term: "Firewall Policy", coc: "COC 3", definition: "A set of rules that defines which network traffic is allowed or denied." },
  { term: "Firewall Rule", coc: "COC 3", definition: "A configuration setting that controls inbound and outbound network traffic." },
  { term: "Firmware", coc: "COC 1", definition: "Software permanently programmed into a hardware device." },
  { term: "Flash Memory", coc: "COC 1", definition: "A type of memory that retains data even without power." },
  { term: "Flooding", coc: "COC 2", definition: "A process of sending excessive data packets to overwhelm a network." },
  { term: "Folder", coc: "COC 1", definition: "A digital container used to organize and store multiple files." },
  { term: "Font", coc: "COC 1", definition: "A design and style of text used in documents and interfaces." },
  { term: "FQDN", coc: "COC 3", definition: "The complete domain name of a specific host in the DNS hierarchy." },
  { term: "FTP Server", coc: "COC 3", definition: "A server that transfers files between systems using the FTP protocol." },
  { term: "Full Backup", coc: "COC 3", definition: "A backup method that copies all files every time it runs." },
  { term: "Gateway", coc: "COC 1", definition: "A device that connects different networks and manages communication between them." },
  { term: "Gateway Protocol", coc: "COC 2", definition: "A type of protocol used by routers to communicate and exchange routing information." },
  { term: "Generator", coc: "COC 3", definition: "A backup power device that provides electricity during extended outages." },
  { term: "Gigabit Ethernet", coc: "COC 2", definition: "An Ethernet standard that supports data transfer rates up to 1 Gbps." },
  { term: "GPO", coc: "COC 3", definition: "A set of policy settings that control system configurations." },
  { term: "GPU", coc: "COC 1", definition: "A processor responsible for rendering images and graphics." },
  { term: "Graphical User Interface", coc: "COC 1", definition: "A visual way of interacting with computers using icons and windows." },
  { term: "Grounding", coc: "COC 1", definition: "The process of connecting an electrical system to the earth to prevent electric shock." },
  { term: "Group Policy", coc: "COC 3", definition: "A feature in Windows that manages user and computer configurations." },
  { term: "Guest Account", coc: "COC 3", definition: "A temporary, limited-access user account on a system." },
  { term: "Guest Machine", coc: "COC 3", definition: "A virtual machine instance running within a host system." },
  { term: "GUI", coc: "COC 3", definition: "A visual interface that allows users to interact with system functions." },
  { term: "Hardware", coc: "COC 1", definition: "The physical components of a computer system." },
  { term: "HDD", coc: "COC 1", definition: "A magnetic storage device used to store operating systems, applications, and files." },
  { term: "HDMI Port", coc: "COC 1", definition: "Used to transmit high-definition video and audio signals." },
  { term: "Heat Sink", coc: "COC 1", definition: "A component that dissipates heat away from the CPU or GPU to prevent overheating." },
  { term: "High Availability", coc: "COC 3", definition: "A design approach that ensures minimal downtime and continuous service." },
  { term: "Host", coc: "COC 2", definition: "Any device connected to a network that has an IP address and can send or receive data." },
  { term: "Host Computer", coc: "COC 1", definition: "A central computer that provides services to other systems or clients." },
  { term: "Host Machine", coc: "COC 3", definition: "The physical computer that runs one or more virtual machines." },
  { term: "Hot Swapping", coc: "COC 1", definition: "The ability to replace hardware components without shutting down the system." },
  { term: "Hotfix", coc: "COC 3", definition: "A quick software patch released to address critical issues." },
  { term: "Hub", coc: "COC 2", definition: "A basic networking device that connects multiple computers in a network and broadcasts data to all." },
  { term: "Hyper-V", coc: "COC 3", definition: "A virtualization platform that allows multiple operating systems to run simultaneously." },
  { term: "Hypervisor", coc: "COC 3", definition: "Software that creates and manages virtual machines." },
  { term: "Icon", coc: "COC 1", definition: "A visual symbol representing a file, program, or function." },
  { term: "IEEE 802.11", coc: "COC 2", definition: "A set of standards for wireless local area networks (Wi-Fi)." },
  { term: "IIS", coc: "COC 3", definition: "A web server software created by Microsoft for hosting websites and web applications." },
  { term: "Incremental Backup", coc: "COC 3", definition: "A backup method that saves only files changed since the last backup." },
  { term: "Input Device", coc: "COC 1", definition: "A hardware component used to enter data or commands into a computer." },
  { term: "Interface", coc: "COC 1", definition: "A point of interaction between a user and a computer system." },
  { term: "Internet Protocol", coc: "COC 1", definition: "A communication protocol that defines how data is sent over the internet." },
  { term: "Intrusion Detection System", coc: "COC 2", definition: "A system that monitors network traffic for suspicious or malicious activities." },
  { term: "Intrusion Prevention System", coc: "COC 2", definition: "A network security system that detects and prevents threats in real time." },
  { term: "IP Address", coc: "COC 2", definition: "A unique identifier assigned to each device on a network." },
  { term: "IP Configuration", coc: "COC 2", definition: "The setup of IP parameters, such as address, subnet mask, and gateway." },
  { term: "IPSec", coc: "COC 3", definition: "A protocol suite for securing IP communications by authenticating and encrypting each packet." },
  { term: "IPV4", coc: "COC 2", definition: "Internet Protocol version 4, which uses 32-bit addresses." },
  { term: "IPV6", coc: "COC 2", definition: "Internet Protocol version 6, which uses 128-bit addresses to support more devices." },
  { term: "ISP", coc: "COC 2", definition: "Internet Service Provider, a company that offers internet access to customers." },
  { term: "Iteration", coc: "COC 1", definition: "The repetition of a process or instruction in computing." },
  { term: "Job Scheduler", coc: "COC 3", definition: "A system tool that automates and schedules repetitive tasks." },
  { term: "Jumper", coc: "COC 1", definition: "A small connector used to configure hardware settings on the motherboard." },
  { term: "Kerberos", coc: "COC 3", definition: "A secure network authentication protocol using secret-key cryptography." },
  { term: "Keyboard", coc: "COC 1", definition: "An input device used to enter text and execute commands." },
  { term: "LAN", coc: "COC 1", definition: "A network that connects computers within a limited geographical area." },
  { term: "Latency", coc: "COC 1", definition: "The delay between sending and receiving data across a network." },
  { term: "LDAP", coc: "COC 3", definition: "A protocol used to access and manage directory information services over an IP network." },
  { term: "Library", coc: "COC 1", definition: "A collection of precompiled routines used by programs." },
  { term: "Link", coc: "COC 1", definition: "A clickable element that directs the user to another document or webpage." },
  { term: "Linux OS", coc: "COC 1", definition: "An open-source OS known for flexibility and stability." },
  { term: "Live CD", coc: "COC 1", definition: "A bootable CD that allows the use of an OS without installation." },
  { term: "Load Balancer", coc: "COC 1", definition: "A system that distributes network traffic evenly across multiple servers." },
  { term: "Load Balancing", coc: "COC 2", definition: "The process of distributing network or application traffic across multiple servers." },
  { term: "Load Distribution", coc: "COC 3", definition: "The process of dividing network or processing tasks among multiple systems." },
  { term: "Local Server", coc: "COC 3", definition: "A server hosted within the same physical network or facility." },
  { term: "Log File", coc: "COC 3", definition: "A text file containing recorded events, errors, or transactions." },
  { term: "Log Management", coc: "COC 3", definition: "The process of collecting, storing, and analyzing log data for system monitoring." },
  { term: "Login Credentials", coc: "COC 1", definition: "The combination of username and password required for authentication." },
  { term: "MAC Address", coc: "COC 2", definition: "A unique hardware identifier assigned to a network interface card." },
  { term: "MAC Filtering", coc: "COC 2", definition: "A network security method that allows or denies access based on MAC addresses." },
  { term: "macOS", coc: "COC 1", definition: "Apple’s proprietary operating system for Mac computers." },
  { term: "Mainframe", coc: "COC 1", definition: "A large, powerful computer used for critical applications and data processing." },
  { term: "Maintenance Schedule", coc: "COC 3", definition: "A planned routine for performing system upkeep and updates." },
  { term: "Malware", coc: "COC 1", definition: "Any program intentionally designed to cause damage to a computer system." },
  { term: "Malware Scanner", coc: "COC 3", definition: "A tool that detects and removes malicious software from servers." },
  { term: "MAN", coc: "COC 2", definition: "A network that covers a larger area than a LAN but smaller than a WAN, typically a city or campus." },
  { term: "Managed Server", coc: "COC 3", definition: "A server maintained by a third-party provider for performance and security." },
  { term: "Memory Slot", coc: "COC 1", definition: "A connector on the motherboard where memory modules are installed." },
  { term: "Micron", coc: "COC 1", definition: "A unit of measurement used to express the thickness of semiconductor layers." },
  { term: "Microphone", coc: "COC 1", definition: "An input device that captures and converts sound waves into electrical signals." },
  { term: "Modem", coc: "COC 1", definition: "A device that converts digital data to analog signals and vice versa for communication." },
  { term: "Monitor", coc: "COC 1", definition: "An output device that displays visual information generated by the computer." },
  { term: "Monitoring Tools", coc: "COC 2", definition: "Software applications used to observe, track, and manage network performance." },
  { term: "Motherboard", coc: "COC 1", definition: "The primary circuit board that connects and allows communication between all computer components." },
  { term: "Motherboard Standoff", coc: "COC 1", definition: "A spacer that prevents the motherboard from touching the metal case." },
  { term: "Mouse", coc: "COC 1", definition: "A pointing device used to interact with the computer interface." },
  { term: "Multimeter", coc: "COC 1", definition: "An electrical instrument used to measure voltage, current, and resistance." },
  { term: "NAS", coc: "COC 3", definition: "A device that provides centralized storage accessible to networked computers." },
  { term: "Network Adapter", coc: "COC 1", definition: "A hardware component that enables a computer to connect to a network." },
  { term: "Network Administrator", coc: "COC 2", definition: "A professional responsible for maintaining and managing computer networks." },
  { term: "Network Analyzer", coc: "COC 2", definition: "A tool used to inspect and evaluate network performance and traffic." },
  { term: "Network Bridge", coc: "COC 2", definition: "A device that connects two local area networks and filters traffic between them." },
  { term: "Network Cable", coc: "COC 1", definition: "A cable that transmits data between network devices." },
  { term: "Network Cable Tester", coc: "COC 2", definition: "A tool used to verify the integrity and connectivity of network cables." },
  { term: "Network Diagnostics", coc: "COC 2", definition: "The process of identifying and resolving problems in a computer network." },
  { term: "Network Diagram", coc: "COC 3", definition: "A graphical representation of a computer network’s layout and connections." },
  { term: "Network Interface", coc: "COC 1", definition: "A point of connection between a computer and a network." },
  { term: "Network Interface Card", coc: "COC 1", definition: "Hardware that allows a computer to connect to a network." },
  { term: "Network Layer", coc: "COC 2", definition: "The third layer in the OSI model responsible for logical addressing and routing." },
  { term: "Network Mapping", coc: "COC 3", definition: "The process of identifying and visualizing connected devices within a network." },
  { term: "Network Policy", coc: "COC 2", definition: "A set of rules that define how network resources are accessed and used." },
  { term: "Network Protocol", coc: "COC 2", definition: "A set of rules that define how data is transmitted across a network." },
  { term: "Network Redundancy", coc: "COC 2", definition: "The inclusion of backup devices and paths to ensure reliability in case of failure." },
  { term: "Network Security", coc: "COC 2", definition: "The practice of protecting network integrity, confidentiality, and accessibility." },
  { term: "Network Server", coc: "COC 3", definition: "A server that provides services such as file sharing and email across a network." },
  { term: "Network Simulation", coc: "COC 2", definition: "The process of modeling network behavior using software for testing and analysis." },
  { term: "Network Topology", coc: "COC 1", definition: "The physical or logical arrangement of a network’s components." },
  { term: "Network Troubleshooting", coc: "COC 2", definition: "The process of diagnosing and resolving issues in computer networks." },
  { term: "Network Virtualization", coc: "COC 2", definition: "The creation of multiple virtual networks within a single physical infrastructure." },
  { term: "NIC Teaming", coc: "COC 3", definition: "Combining multiple network adapters to increase bandwidth and redundancy." },
  { term: "Node", coc: "COC 1", definition: "Any active device connected to a network, such as a computer or printer." },
  { term: "Northbridge", coc: "COC 1", definition: "A motherboard chip that connects the CPU to memory and graphics components." },
  { term: "NTFS", coc: "COC 1", definition: "A file system developed by Microsoft for Windows-based computers." },
  { term: "NTP Server", coc: "COC 3", definition: "A server that synchronizes clocks across network devices." },
  { term: "Operating System", coc: "COC 1", definition: "Software that manages computer hardware and software resources." },
  { term: "Operating System Deployment", coc: "COC 3", definition: "The process of installing and configuring an OS across multiple systems." },
  { term: "Optical Drive", coc: "COC 1", definition: "Reads and writes data from CDs, DVDs, and Blu-ray discs." },
  { term: "Output Device", coc: "COC 1", definition: "A hardware component that displays or transmits processed data to the user." },
  { term: "Overclocking", coc: "COC 1", definition: "The practice of increasing a processor’s speed beyond its default setting." },
  { term: "Packet", coc: "COC 2", definition: "A formatted unit of data carried by a packet-switched network." },
  { term: "Packet Filtering", coc: "COC 2", definition: "A method used by firewalls to control data flow based on header information." },
  { term: "Packet Sniffer", coc: "COC 2", definition: "A tool used to capture and analyze packets of data transmitted over a network." },
  { term: "Partition", coc: "COC 1", definition: "A defined section of a storage drive used to organize and manage data." },
  { term: "Password Policy", coc: "COC 3", definition: "A set of security rules that govern the creation and use of passwords." },
  { term: "Patch", coc: "COC 1", definition: "A small update designed to fix or improve existing software." },
  { term: "Patch Cable", coc: "COC 2", definition: "A short cable used to connect devices to a network switch or patch panel." },
  { term: "Patch Management", coc: "COC 2", definition: "The process of updating software and firmware to fix bugs and security issues." },
  { term: "Patch Panel", coc: "COC 2", definition: "A mounted hardware assembly containing ports for network cable connections." },
  { term: "Patch Rollback", coc: "COC 3", definition: "The process of undoing or removing an installed patch or update." },
  { term: "PC Case", coc: "COC 1", definition: "The outer shell that houses and protects all internal computer components." },
  { term: "Peer-to-Peer Network", coc: "COC 2", definition: "A network model where each device shares resources directly without a central server." },
  { term: "Performance Counter", coc: "COC 3", definition: "A tool that measures system resource usage in real time." },
  { term: "Peripheral", coc: "COC 1", definition: "External hardware connected to a computer to enhance its functionality." },
  { term: "Peripheral Component", coc: "COC 1", definition: "An external hardware part connected to a computer to expand functionality." },
  { term: "Peripheral Device", coc: "COC 1", definition: "External hardware like printers, scanners, or keyboards that connect to a computer." },
  { term: "Peripheral Devices", coc: "COC 1", definition: "External input or output devices connected to a computer system." },
  { term: "Permission Settings", coc: "COC 3", definition: "Configurations that define what users can access or modify." },
  { term: "Phishing", coc: "COC 1", definition: "A fraudulent attempt to obtain sensitive information through deceptive emails or messages." },
  { term: "Physical Server", coc: "COC 3", definition: "A single hardware machine that runs server software and hosts resources." },
  { term: "Ping", coc: "COC 2", definition: "A command used to test the reachability of a host and measure latency." },
  { term: "Ping Command", coc: "COC 1", definition: "A network tool used to test connectivity between two systems." },
  { term: "Ping Response", coc: "COC 3", definition: "A reply sent from a device to confirm network connectivity." },
  { term: "Ping Test", coc: "COC 3", definition: "A network utility used to verify connectivity between systems." },
  { term: "Pixel", coc: "COC 1", definition: "The smallest controllable element of a digital image or display." },
  { term: "Pixel Density", coc: "COC 1", definition: "The number of pixels per inch on a display screen." },
  { term: "Plug and Play", coc: "COC 1", definition: "A feature that automatically detects and configures hardware devices." },
  { term: "Port", coc: "COC 1", definition: "An interface or connection point for external devices." },
  { term: "Port Forwarding", coc: "COC 2", definition: "A method of redirecting communication requests from one address and port number to another." },
  { term: "Port Security", coc: "COC 2", definition: "A network switch feature that restricts access based on device MAC addresses." },
  { term: "Power Adapter", coc: "COC 1", definition: "A device that converts electrical energy to power electronic components." },
  { term: "Power Management", coc: "COC 1", definition: "The process of controlling power consumption in computing devices." },
  { term: "Power Supply", coc: "COC 1", definition: "A hardware component that provides regulated power to all internal parts of the computer." },
  { term: "Power Supply Tester", coc: "COC 1", definition: "A device used to check the output voltages of a power supply unit." },
  { term: "Power Surge", coc: "COC 1", definition: "A sudden increase in voltage that can damage electronic components." },
  { term: "Printer", coc: "COC 1", definition: "An output device that produces a physical copy of digital documents." },
  { term: "Private IP", coc: "COC 2", definition: "An IP address used within a private network, not accessible from the internet." },
  { term: "Processor", coc: "COC 1", definition: "The central unit that interprets and executes instructions from hardware and software." },
  { term: "Processor Speed", coc: "COC 1", definition: "The rate at which a processor executes instructions." },
  { term: "Program", coc: "COC 1", definition: "A set of coded instructions that perform a specific task on a computer." },
  { term: "Protocol", coc: "COC 1", definition: "A set of rules governing data communication between devices." },
  { term: "Protocol Address", coc: "COC 1", definition: "A numerical label assigned to each device connected to a network." },
  { term: "Proxy Configuration", coc: "COC 2", definition: "The setup of a proxy server to filter or monitor internet traffic." },
  { term: "Proxy Server", coc: "COC 2", definition: "A server that acts as an intermediary between a client and external servers." },
  { term: "Public IP", coc: "COC 2", definition: "An IP address that allows devices to be accessible over the internet." },
  { term: "QoS", coc: "COC 2", definition: "A technology that manages network traffic to ensure performance for critical applications." },
  { term: "RAID", coc: "COC 3", definition: "A method of combining multiple drives for data redundancy and performance." },
  { term: "RAID Controller", coc: "COC 3", definition: "Hardware or software that manages RAID configurations." },
  { term: "RAM", coc: "COC 1", definition: "Volatile memory used for temporary data storage during processing." },
  { term: "RAM Slot", coc: "COC 1", definition: "A socket on the motherboard where RAM modules are installed." },
  { term: "Read-Only Memory", coc: "COC 1", definition: "Non-volatile memory that stores essential startup instructions for the computer." },
  { term: "Reboot", coc: "COC 1", definition: "The process of restarting a computer to refresh its operating system." },
  { term: "Registry", coc: "COC 1", definition: "A database that stores configuration settings for the operating system." },
  { term: "Remote Access", coc: "COC 2", definition: "The ability to connect and manage a computer or network from a distant location." },
  { term: "Remote Desktop", coc: "COC 3", definition: "A Microsoft protocol that allows remote access to a graphical desktop environment." },
  { term: "Replication", coc: "COC 3", definition: "The process of copying and maintaining database or file data across systems." },
  { term: "Resolution", coc: "COC 1", definition: "The number of pixels displayed on the screen horizontally and vertically." },
  { term: "Resource Monitor", coc: "COC 3", definition: "A system tool used to track CPU, memory, disk, and network usage." },
  { term: "Restore", coc: "COC 1", definition: "To bring back data or settings from a backup." },
  { term: "Restore Point", coc: "COC 3", definition: "A system state backup used to revert a server to a previous configuration." },
  { term: "RJ11", coc: "COC 2", definition: "A standard connector used for telephone lines." },
  { term: "RJ45", coc: "COC 2", definition: "A standard connector used for Ethernet networking cables." },
  { term: "Root Directory", coc: "COC 3", definition: "The top-level folder in a file system hierarchy." },
  { term: "Router", coc: "COC 1", definition: "A device that forwards data packets between computer networks." },
  { term: "Router Configuration", coc: "COC 2", definition: "The process of setting up a router’s parameters and routing tables." },
  { term: "Routing", coc: "COC 2", definition: "The process of selecting paths in a network along which to send network traffic." },
  { term: "Routing Protocol", coc: "COC 2", definition: "A protocol that determines how routers communicate and exchange information." },
  { term: "Routing Table", coc: "COC 2", definition: "A database in a router that stores routes for network destinations." },
  { term: "Safe Mode", coc: "COC 1", definition: "A diagnostic mode that loads only essential drivers for troubleshooting." },
  { term: "SAN", coc: "COC 3", definition: "A high-speed network that provides block-level data storage." },
  { term: "Scalability", coc: "COC 3", definition: "The ability of a system to handle increasing workloads efficiently." },
  { term: "Scanner", coc: "COC 1", definition: "An input device that converts physical documents into digital form." },
  { term: "Screwdriver", coc: "COC 1", definition: "A hand tool used for tightening or loosening screws." },
  { term: "SD Card", coc: "COC 1", definition: "A small storage device used in cameras, smartphones, and computers." },
  { term: "Secure Socket Layer", coc: "COC 2", definition: "A standard security technology for establishing an encrypted link between a web server and browser." },
  { term: "Security Audit", coc: "COC 3", definition: "A review process that evaluates the security measures of a system." },
  { term: "Security Patch", coc: "COC 3", definition: "A software update that fixes security vulnerabilities." },
  { term: "Serial Port", coc: "COC 1", definition: "A port that transfers data one bit at a time between devices." },
  { term: "Server", coc: "COC 1", definition: "A system that provides data or services to other computers over a network." },
  { term: "Server Farm", coc: "COC 3", definition: "A collection of servers housed in one location to handle high workloads." },
  { term: "Server Maintenance", coc: "COC 3", definition: "Routine tasks performed to ensure optimal server performance." },
  { term: "Server Monitoring", coc: "COC 3", definition: "The practice of continuously checking the health and uptime of servers." },
  { term: "Server Rack", coc: "COC 3", definition: "A frame designed to hold multiple servers and networking equipment." },
  { term: "Server Room", coc: "COC 3", definition: "A dedicated space that houses physical servers and network hardware." },
  { term: "Service Account", coc: "COC 3", definition: "A specialized account used by applications or services to run processes." },
  { term: "Service Management", coc: "COC 3", definition: "The practice of managing IT services to meet business needs." },
  { term: "Session Layer", coc: "COC 2", definition: "The fifth layer of the OSI model that manages communication sessions." },
  { term: "Session Timeout", coc: "COC 3", definition: "A security setting that logs users out after a period of inactivity." },
  { term: "Shell Access", coc: "COC 3", definition: "Command-line access to a server’s operating system." },
  { term: "Shutdown", coc: "COC 1", definition: "The process of safely turning off a computer to prevent data loss." },
  { term: "Signal", coc: "COC 2", definition: "An electrical or optical transmission used to convey data over a medium." },
  { term: "Simple Mail Transfer Protocol", coc: "COC 2", definition: "A protocol used for sending emails between servers." },
  { term: "Simple Network Management Protocol", coc: "COC 2", definition: "A protocol for monitoring and managing network devices." },
  { term: "Slot Cover", coc: "COC 1", definition: "A removable plate that covers unused expansion slots on the computer case." },
  { term: "SMTP Server", coc: "COC 2", definition: "A mail server that handles outgoing email messages." },
  { term: "SNMP", coc: "COC 3", definition: "A protocol for monitoring and managing network devices." },
  { term: "SNMP Manager", coc: "COC 2", definition: "A system that collects and manages information from network devices using SNMP." },
  { term: "Software", coc: "COC 1", definition: "Programs and applications that instruct the computer on what to do." },
  { term: "Software Deployment", coc: "COC 3", definition: "The process of installing and updating software on multiple machines." },
  { term: "Sound Card", coc: "COC 1", definition: "A hardware component that processes audio signals for playback or recording." },
  { term: "Speaker", coc: "COC 1", definition: "An output device that converts digital signals into audible sound." },
  { term: "SQL Server", coc: "COC 3", definition: "A relational database management system developed by Microsoft." },
  { term: "SSD", coc: "COC 1", definition: "A fast storage device that uses flash memory instead of spinning disks." },
  { term: "SSL Certificate", coc: "COC 2", definition: "A digital certificate that authenticates a website’s identity and enables HTTPS." },
  { term: "Static Electricity", coc: "COC 1", definition: "An imbalance of electric charges that can damage sensitive electronics." },
  { term: "Static IP", coc: "COC 3", definition: "A permanent IP address assigned to a device or server." },
  { term: "Static Shield Bag", coc: "COC 1", definition: "A protective bag used to store electronic components safely." },
  { term: "Storage Capacity", coc: "COC 3", definition: "The maximum amount of data that can be stored on a system." },
  { term: "Storage Device", coc: "COC 1", definition: "Hardware used to save data permanently or temporarily, such as SSD or HDD." },
  { term: "Subnet", coc: "COC 2", definition: "A subdivided segment of an IP network that improves organization and security." },
  { term: "Subnet Mask", coc: "COC 2", definition: "A numerical label used to divide IP addresses into network and host portions." },
  { term: "Surge Protector", coc: "COC 1", definition: "A device that safeguards electronics from voltage spikes." },
  { term: "Switch", coc: "COC 2", definition: "A device that connects and manages multiple computers within a LAN." },
  { term: "System Boot", coc: "COC 1", definition: "The process of starting up a computer and loading the operating system." },
  { term: "System Log", coc: "COC 2", definition: "A record of events and activities occurring within a computer or network system." },
  { term: "System Logs", coc: "COC 3", definition: "Recorded events that provide information about server operations." },
  { term: "System Restore", coc: "COC 1", definition: "A Windows feature that allows recovery from system errors without losing personal data." },
  { term: "System Unit", coc: "COC 1", definition: "The main body of a computer containing the motherboard, CPU, and other components." },
  { term: "System Update", coc: "COC 3", definition: "The process of installing the latest patches and improvements to an operating system." },
  { term: "Task Manager", coc: "COC 1", definition: "A Windows utility used to monitor and manage running applications and processes." },
  { term: "Tast Manager", coc: "COC 1", definition: "A system utility used to monitor running applications, processes, and system performance." },
  { term: "TCP", coc: "COC 2", definition: "A core protocol that ensures reliable, ordered, and error-checked delivery of data." },
  { term: "TCP/IP", coc: "COC 2", definition: "A set of communication protocols used to interconnect network devices." },
  { term: "Telnet", coc: "COC 2", definition: "A network protocol that allows remote login and command execution on another device." },
  { term: "Terminal Server", coc: "COC 3", definition: "A server that provides remote desktop access to multiple users simultaneously." },
  { term: "Thermal Paste", coc: "COC 1", definition: "A material applied between the CPU and heat sink to enhance heat transfer." },
  { term: "Throughput", coc: "COC 2", definition: "The actual rate at which data is successfully transmitted over a network." },
  { term: "Toolkit", coc: "COC 1", definition: "A collection of tools used for assembling or repairing computers." },
  { term: "Topology", coc: "COC 2", definition: "The physical or logical arrangement of devices in a network." },
  { term: "Topology Diagram", coc: "COC 3", definition: "A visual representation of a network’s physical and logical structure." },
  { term: "Traceroute", coc: "COC 2", definition: "A network diagnostic tool used to track the path data takes from source to destination." },
  { term: "Traceroute Command", coc: "COC 2", definition: "A diagnostic command used to display the route data takes through the network." },
  { term: "Traffic Management", coc: "COC 3", definition: "The process of controlling data flow to optimize network performance." },
  { term: "Transmission Delay", coc: "COC 2", definition: "The time required for data to travel from source to destination." },
  { term: "Transmission Media", coc: "COC 2", definition: "The physical pathways, such as cables or air, through which data travels." },
  { term: "Troubleshooting", coc: "COC 1", definition: "The process of identifying and solving computer hardware or software problems." },
  { term: "UDP", coc: "COC 2", definition: "A connectionless protocol that allows fast, but unreliable, data transmission." },
  { term: "Upload Speed", coc: "COC 2", definition: "The rate at which data is sent from a device to the internet." },
  { term: "Uptime", coc: "COC 3", definition: "The total time a server or system has been running without interruption." },
  { term: "URL", coc: "COC 2", definition: "The address used to identify and access resources on the internet." },
  { term: "USB", coc: "COC 1", definition: "A standard interface for connecting peripheral devices to computers." },
  { term: "USB Flash Drive", coc: "COC 1", definition: "A removable data storage device that uses flash memory." },
  { term: "User Access Control", coc: "COC 3", definition: "A Windows security feature that prevents unauthorized system changes." },
  { term: "User Account", coc: "COC 3", definition: "An identity established in a system that allows access to its resources." },
  { term: "User Authentication", coc: "COC 2", definition: "The process of verifying the identity of a user attempting to access a network." },
  { term: "User Management", coc: "COC 3", definition: "The administrative process of creating and maintaining user accounts." },
  { term: "User Profile", coc: "COC 3", definition: "A collection of user-specific settings and preferences on a system." },
  { term: "VGA Port", coc: "COC 1", definition: "An analog connector used to connect display monitors." },
  { term: "Virtual Directory", coc: "COC 3", definition: "A folder in a web server that maps to a physical location on disk." },
  { term: "Virtual LAN", coc: "COC 2", definition: "A network configuration that allows segmentation of devices into logical groups." },
  { term: "Virtual Machine", coc: "COC 2", definition: "A software-based emulation of a physical computer system." },
  { term: "Virtual Memory", coc: "COC 3", definition: "A memory management technique that uses disk space as RAM extension." },
  { term: "Virtual Network", coc: "COC 3", definition: "A logically isolated network created within a cloud or virtualization environment." },
  { term: "Virtual Private Network", coc: "COC 2", definition: "A secure connection over the internet that protects data through encryption." },
  { term: "Virtual Server", coc: "COC 3", definition: "A server that runs in a virtualized environment rather than on physical hardware." },
  { term: "Virus", coc: "COC 1", definition: "Malicious software that replicates and spreads between systems." },
  { term: "Virus Definition", coc: "COC 3", definition: "A database of known malware signatures used by antivirus programs." },
  { term: "Virus Scanner", coc: "COC 1", definition: "Software that detects and removes malicious programs from computers." },
  { term: "VM Host", coc: "COC 3", definition: "A physical server that runs one or more virtual machines." },
  { term: "VM Snapshot", coc: "COC 3", definition: "A saved state of a virtual machine at a specific point in time." },
  { term: "VPN Server", coc: "COC 2", definition: "A server that establishes secure and encrypted connections for remote users." },
  { term: "Vulnerability Assessment", coc: "COC 3", definition: "A process of identifying and evaluating security weaknesses." },
  { term: "WAN", coc: "COC 2", definition: "A network that extends over a large geographical area, connecting multiple LANs." },
  { term: "Web Application", coc: "COC 3", definition: "A software program that runs on a web server and is accessed through a browser." },
  { term: "Web Browser", coc: "COC 1", definition: "A program used to access and view websites on the internet." },
  { term: "Web Hosting", coc: "COC 2", definition: "A service that provides storage and access for websites on the internet." },
  { term: "Web Server", coc: "COC 2", definition: "A computer system that hosts websites and delivers web pages to users through a browser." },
  { term: "Wi-Fi", coc: "COC 2", definition: "A technology that allows wireless devices to connect to a local area network." },
  { term: "Wi-Fi Adapter", coc: "COC 1", definition: "A hardware device that enables a computer to connect to wireless networks." },
  { term: "Wi-Fi Analyzer", coc: "COC 2", definition: "A tool used to scan, test, and troubleshoot wireless networks." },
  { term: "Windows Firewall", coc: "COC 3", definition: "A built-in Windows security feature that filters network traffic." },
  { term: "Windows OS", coc: "COC 1", definition: "A graphical operating system developed by Microsoft Corporation." },
  { term: "Windows PowerShell", coc: "COC 3", definition: "A command-line shell and scripting language for Windows system administration." },
  { term: "Windows Registry", coc: "COC 3", definition: "A hierarchical database that stores configuration settings and options." },
  { term: "WINS Server", coc: "COC 2", definition: "A server that resolves NetBIOS names to IP addresses in Windows networks." },
  { term: "Wired Equivalent Privacy", coc: "COC 2", definition: "An older wireless network security protocol replaced by WPA and WPA2." },
  { term: "Wired Network", coc: "COC 2", definition: "A network where devices are connected through physical cables." },
  { term: "Wireless Access Point", coc: "COC 2", definition: "A device that allows wireless devices to connect to a wired network." },
  { term: "Wireless Adapter", coc: "COC 2", definition: "A hardware component that allows a computer to connect to wireless networks." },
  { term: "Wireless Fidelity", coc: "COC 2", definition: "A technology that enables wireless networking of digital devices." },
  { term: "Wireless Network", coc: "COC 2", definition: "A network that uses radio waves to connect devices without physical cables." },
  { term: "Wireless Router", coc: "COC 2", definition: "A device that combines the functions of a router and a wireless access point." },
  { term: "Wireshark", coc: "COC 1", definition: "A software used to monitor and analyze network traffic." },
  { term: "WLAN Controller", coc: "COC 2", definition: "A device that manages multiple access points within a wireless network." },
  { term: "Workflow Automation", coc: "COC 3", definition: "The use of technology to streamline and automate repetitive processes." },
  { term: "Workgroup", coc: "COC 2", definition: "A group of computers connected in a peer-to-peer network that shares files and resources." },
  { term: "Workstation", coc: "COC 1", definition: "A high-performance computer designed for technical or scientific tasks." },
  { term: "Worm", coc: "COC 1", definition: "A self-replicating malware that spreads across networks without human interaction." },
  { term: "WPA2", coc: "COC 2", definition: "A security protocol that encrypts data on wireless networks." },
  { term: "WPA3", coc: "COC 2", definition: "An advanced wireless security protocol offering stronger encryption and privacy." },
  { term: "XML", coc: "COC 2", definition: "A markup language that defines a set of rules for encoding documents in a readable format." },
  { term: "Zigbee", coc: "COC 2", definition: "A wireless communication standard designed for low-power and low-data-rate applications." },
  { term: "Zip File", coc: "COC 1", definition: "A file that contains one or more files compressed to reduce size." },
  { term: "Zone File", coc: "COC 3", definition: "A text file that defines the mappings of domain names to IP addresses." },
  { term: "Zone-Based Firewall", coc: "COC 2", definition: "A firewall configuration that groups interfaces into security zones for traffic control." },
  { term: "Zoom", coc: "COC 1", definition: "An online communication platform used for video meetings and collaboration." }
];